### ISSUE TITLE
Support for Reading Back Compute Shader Input Buffers/Textures

### ISSUE THREAD

**Issue by Twinklebear** [brendan-duncan/webgpu_inspector#5]
Thanks for this incredible tool! I've been trying it out on a few of my projects and it's really useful.

One thing I noticed that was missing was support for reading back inputs to compute shaders (uniform/storage buffers, textures), while that is supported for regular draw calls. For example, on my project: https://github.com/Twinklebear/webgpu-marching-cubes , if I capture a frame running the compute passes I can't inspect the buffer contents going to the compute shaders (the "show data" button is missing, or for uniform buffers, no data is shown).

For example, uniform buffer content not shown:
<img width="1509" alt="Screenshot 2024-04-29 at 8 44 30 AM" src="https://github.com/brendan-duncan/webgpu_inspector/assets/1522476/4e462bbf-4114-4510-b9d5-a4e253fed330">

Storage buffer content not shown:
<img width="1512" alt="Screenshot 2024-04-29 at 8 46 14 AM" src="https://github.com/brendan-duncan/webgpu_inspector/assets/1522476/8f48d8ba-0044-4096-be59-a9ffd1ceb525">

But it is visible for inputs to draw calls:

<img width="1512" alt="Screenshot 2024-04-29 at 8 45 28 AM" src="https://github.com/brendan-duncan/webgpu_inspector/assets/1522476/0fea1d07-80d9-4882-88b7-6e6a3c6b76d5">

You can reproduce this by setting the capture to delay a bit and capture frame 200 or so, then just move the isovalue slider back and forth to have the app be running the compute passes on the frame that gets captured.

Would it be possible to get support for compute shader input readback added as well?

I've been using the version installed from the Chrome webstore, which looks to be 0.1.1

**Comment by brendan-duncan** [comment]
Weird, it should be capturing the data for the compute dispatches. I'll look into it, get it sorted out.

**Comment by brendan-duncan** [comment]
Looks like something caused the buffer reads to get stalled, that's why the capture status bar at the top still has the "Loading Buffers 29 Data Chunks 29" status message. I'm guessing at least some of those still pending buffers are from the compute dispatch.

Because the devtools page is in a separate process from the browser page, it has to send all of the data over to the panel via messages, and since messages have size limits, it breaks up the data into chunks. Something either interrupted the messages, or it lost track of things. It seems like the browser page itself finished sending the buffer data, since I put the capture status info in that frame/timer overlay on the page, so the problem must be on the devtools panel listener side.

I'll dig into it soon, hopefully sometime today. I'm curious what's going on there.

**Comment by Twinklebear** [comment]
Would the max buffer size effect this? I just noticed that some of the storage buffers were over the default max bytes (1001472 vs 262144) so I increased it to 1MB but that loading chunks text is still stuck on "Loading Buffers: 28 Data Chunks: 52".

Thanks for looking into this!

**Comment by brendan-duncan** [comment]
I don't think the max buffer size is affecting it, that should just skip them from being captured on the page side to try and keep the capture from taking too long. It's probably something like an error that keeps the rest of the buffers from finishing being read in. Hopefully it'll be a quick fix, just have to do some day job work first :-)

**Comment by brendan-duncan** [comment]
I figured out where the missing buffer data is going. There's a bad assumption in the "listen for incoming buffer data" code. It assumed the command list message has already come in, because it associates the buffer data with a command. But in this case the buffer data message was coming in before the command list message. I'll get that fixed up.

**Comment by brendan-duncan** [comment]
I pushed a fix to git. It deals with the out-of-order messages where the buffer data is coming in before the commands. I think it could be done in a better way, but it seems to be working ok. For my testing, instead of doing the "capture frame 200 and scrub the Isovalue", I just had it capture frame 0.

![image](https://github.com/brendan-duncan/webgpu_inspector/assets/3642099/1080dde7-3d17-42f4-b1be-ec21c66b6a2a)

**Comment by Twinklebear** [comment]
Awesome, it works! I hit an error when using the build in the repo but after rebuilding the source, I'm able to see the data as well. I didn't realize I could just hit capture to load on start instead of start -> then clicking capture, that also works for just capturing frame 0.

The page hangs a bit when opening up some of the large buffers I have here, but that's probably something for a future issue.

**Comment by brendan-duncan** [comment]
I'll get a chrome store update out sometime soon. Got some other stuff to get through first.

I'll see if there's a better way to display larger buffers, maybe paginate the results or something. Trying to fit everything into a unified view like this makes it a bit challenging, but I wanted to try to avoid the tab hell that is RenderDoc.

**Comment by Twinklebear** [comment]
I think pagination would work well for showing these kind of buffers, some way to jump to an index or search for values would also be handy for finding stuff in large buffers.

**Comment by brendan-duncan** [comment]
If you can make a new ticket for improving large buffer views, then I won't forget to get back to working on it.

**Comment by Twinklebear** [comment]
I opened https://github.com/brendan-duncan/webgpu_inspector/issues/6 👍
